config/routes.rb
Rails.application.routes.draw do
  resources :shrinks
  get "/:shortname", to: "shrinks#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shrink.rb
class Shrink < ApplicationRecord

  def compress_and_check_url
    make_properurl # generate proper url
  	unless check_properurl.nil? # if proper url is already present
      false
    else # if proper url is not present then generate random url
      compress_url
      true
    end
  end

  def compress_url
  	url = ([*('a'..'z'), *('0'..'9')]).sample(7).join
    data = Shrink.where(shortname: url).last
    self.compress_url if data.present? # if random generated url is already presented in the table
    self.shortname = url
  end

  def check_properurl
    Shrink.find_by_proper_url(self.proper_url)
  end

  def make_properurl
    org_name = self.originalname.downcase.strip.gsub %r{(?<!:)/+(?=/)}, '' # removing all repeatitive forward slash such as www.////facebook.com//hi/s//234//
    org_name = org_name.gsub(/(https?:\/\/)|(www\.)/,"")      # removing  https:// or http:// from the url
    # removing slash in last position after com such as: www.google.com/ or google.com/
    org_name.slice!(-1) if org_name[-1] == "/"
    if org_name.include?(".com") # if url is google or www.google
      self.proper_url = "https://www." + org_name
    else
      self.proper_url = "https://www." + org_name + ".com" 
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shrinks_controller.rb
class ShrinksController < ApplicationController
  before_action :set_shrink, only: [ :edit, :update, :destroy]

  # GET /shrinks
  # GET /shrinks.json
  def index
    @shrinks = Shrink.all
  end

  # GET /shrinks/1
  # GET /shrinks/1.json
  def show
    @shrink = Shrink.find_by_shortname(params["shortname"])
    redirect_to @shrink.proper_url
  end

  # GET /shrinks/new
  def new
    @shrink = Shrink.new
  end

  # GET /shrinks/1/edit
  def edit
  end

  # POST /shrinks
  # POST /shrinks.json
  def create
    @shrink = Shrink.new
    @shrink.originalname = params["shrink"]["originalname"]    
    respond_to do |format|
      if @shrink.compress_and_check_url
        if @shrink.save
          format.html { redirect_to shrinks_path, notice: 'Shrink was successfully created.' }
          format.json { render :show, status: :created, location: @shrink }
        else
          format.html { render :new }
          format.json { render json: @shrink.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to shrinks_path, notice: 'Url is already present.' }
      end
    end
  end

  # PATCH/PUT /shrinks/1
  # PATCH/PUT /shrinks/1.json
  def update
    respond_to do |format|
      if @shrink.update(shrink_params)
        format.html { redirect_to @shrink, notice: 'Shrink was successfully updated.' }
        format.json { render :show, status: :ok, location: @shrink }
      else
        format.html { render :edit }
        format.json { render json: @shrink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shrinks/1
  # DELETE /shrinks/1.json
  def destroy
    @shrink.destroy
    respond_to do |format|
      format.html { redirect_to shrinks_url, notice: 'Shrink was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shrink
      @shrink = Shrink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shrink_params
      params.require(:shrink).permit(:originalname, :shortname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shrinks_helper.rb
module ShrinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shorten</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shrinks/_form.html.erb
<%= form_with(model: shrink, local: true) do |form| %>
  <% if shrink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shrink.errors.count, "error") %> prohibited this shrink from being saved:</h2>

      <ul>
      <% shrink.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.text_field :originalname %>
    <%= form.submit %>

  </div>
<% end %>

app/views/shrinks/edit.html.erb
<h1>Editing Shrink</h1>
<%= form_with(model: @shrink, local: true) do |form| %>
  <% if @shrink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shrink.errors.count, "error") %> prohibited this shrink from being saved:</h2>

      <ul>
      <% @shrink.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.text_field :originalname %>
    <%= form.submit %>

  </div>
<% end %>

<%= link_to 'Show', @shrink %> |
<%= link_to 'Back', shrinks_path %>

app/views/shrinks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shrinks</h1>

<table cellspacing="50" >
  <thead >
    <tr >
      <th>Original Url </th>
      <th> Short Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shrinks.each do |shrink| %>
      <tr>
        <td><%= shrink.originalname %></td>
        <td><%= shrink.shortname %></td>
        <td><%#= link_to 'Show', shrink %></td>
        <td><%#= link_to 'Edit', edit_shrink_path(shrink) %></td>
        <td><%= link_to 'Destroy', shrink, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shrink', new_shrink_path %>

app/views/shrinks/new.html.erb
<h1>New Shrink</h1>

<%= render 'form', shrink: @shrink %>

<%= link_to 'Back', shrinks_path %>

app/views/shrinks/show.html.erb
<p id="notice"><%= notice %></p>
<%= "Original url is:  #{@shrink.originalname}" %>
<br>
<%= "Short url is:  #{@shrink.shortname}" %>
<br>
<%#= link_to 'Edit', edit_shrink_path(@shrink) %> |
<%= link_to 'Back', shrinks_path %>
<%#= redirect_to @shrink.originalname %>